matrix:
  - name: spelling
    spellchecker: hunspell
    sources:
    - index.md
    - "./_includes/opening_box.html"
    dictionary:
      wordlists:
      - ignored_words.txt
    pipeline:
    - pyspelling.filters.markdown:
    - pyspelling.filters.html:
        comments: false