matrix:
  - name: spelling
    spellchecker: hunspell
    sources:
    - "./_site/index.html"
    dictionary:
      wordlists:
      - ignored_words.txt
    pipeline:
    - pyspelling.filters.html:
        comments: false
        ignores:
          - ".citation"